"use client";
import { Suspense, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { api, type ReceiptData } from "@/lib/api";

const BASE = process.env.NEXT_PUBLIC_API_BASE ?? "http://localhost:4100";
const month = (iso: string) => new Date(`${String(iso).slice(0, 10)}T00:00:00`).toLocaleDateString("en-IN", { month: "long", year: "numeric" });
const inr = (n: number) => "₹" + Math.round(n).toLocaleString("en-IN");

/**
 * Print-friendly rent receipts (HRA paperwork).
 *   ?id=<rentId>            one receipt (owner-authed; or +&t=<token> for tenants)
 *   ?assetId=<id>&fy=2025   the FY25-26 bundle, one receipt per page (owner-authed)
 */
export default function ReceiptPage() {
  return (
    <Suspense fallback={<div />}>
      <ReceiptView />
    </Suspense>
  );
}

function ReceiptView() {
  const q = useSearchParams();
  const id = q.get("id");
  const assetId = q.get("assetId");
  const fy = q.get("fy");
  const tenantToken = q.get("t");

  const [receipts, setReceipts] = useState<ReceiptData[] | null>(null);
  const [err, setErr] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    (async () => {
      try {
        if (id && tenantToken) {
          const res = await fetch(`${BASE}/api/tenant/receipts/${id}`, { headers: { "x-tenant-token": tenantToken } });
          if (!res.ok) throw new Error("This receipt link is not valid.");
          setReceipts([await res.json()]);
        } else if (id) {
          setReceipts([await api.rentReceipt(id)]);
        } else if (assetId && fy) {
          setReceipts(await api.receiptsForYear(assetId, Number(fy)));
        } else {
          setErr("Nothing to show — open a receipt from the Rent tab.");
        }
      } catch (e: any) { setErr(e.message ?? "Could not load the receipt"); }
    })();
  }, [id, assetId, fy, tenantToken]);

  async function fileIntoVault() {
    if (!id) return;
    try { await api.saveReceiptToVault(id); setSaved(true); }
    catch (e: any) { setErr(e.message ?? "Could not save"); }
  }

  if (err) return <div style={{ maxWidth: 640, margin: "60px auto", fontFamily: "Georgia, serif" }}>{err}</div>;
  if (!receipts) return <div />;

  return (
    <div style={{ maxWidth: 680, margin: "0 auto", padding: "24px 20px", fontFamily: "Georgia, serif", color: "#16243f" }}>
      <style>{`@media print { .noprint { display: none !important; } .receipt { page-break-after: always; } } `}</style>
      <div className="noprint" style={{ display: "flex", gap: 10, justifyContent: "flex-end", marginBottom: 8 }}>
        {id && !tenantToken && (
          <button onClick={fileIntoVault} disabled={saved}
            style={{ font: "inherit", fontSize: 14, padding: "8px 14px", cursor: "pointer", borderRadius: 8, border: "1px solid #cfd4dd", background: "#fff" }}>
            {saved ? "Filed into documents ✓" : "File into documents"}
          </button>
        )}
        <button onClick={() => window.print()}
          style={{ font: "inherit", fontSize: 14, padding: "8px 14px", cursor: "pointer", borderRadius: 8, border: 0, background: "#16243f", color: "#fff" }}>
          Print / Save as PDF
        </button>
      </div>

      {receipts.length === 0 && <p>No collected rent in that financial year yet.</p>}
      {receipts.map((d) => (
        <div className="receipt" key={d.rentId} style={{ marginBottom: 40 }}>
          <h1 style={{ fontSize: 22, borderBottom: "2px solid #16243f", paddingBottom: 8 }}>Rent Receipt — {month(d.periodMonth)}</h1>
          <table style={{ width: "100%", borderCollapse: "collapse", margin: "16px 0", fontSize: 15 }}>
            <tbody>
              <Row k="Received from (tenant)" v={d.tenantName ?? "—"} />
              <Row k="Paid to (landlord)" v={d.landlordName ?? d.householdName} />
              <Row k="Property" v={`${d.propertyName}${d.propertyAddress ? " — " + d.propertyAddress : ""}`} />
              <Row k="Rent period" v={month(d.periodMonth)} />
              <Row k="Gross rent" v={inr(d.amountDue)} />
              {d.tds > 0 && <Row k="TDS deducted" v={inr(d.tds)} />}
              <Row k={d.tds > 0 ? "Net rent received" : "Rent received"} v={inr(d.collected ?? d.netDue)} bold />
              <Row k="Received on" v={d.collectedOn ?? "—"} />
            </tbody>
          </table>
          <div style={{ color: "#8a92a0", fontSize: 12, marginTop: 24 }}>
            Generated by Kunatra for {d.householdName}. Landlord PAN available from the landlord on request where required for HRA claims.
          </div>
        </div>
      ))}
    </div>
  );
}

function Row({ k, v, bold }: { k: string; v: string; bold?: boolean }) {
  return (
    <tr>
      <td style={{ padding: "7px 4px", borderBottom: "1px solid #e3e6ec", color: "#5a6473", width: "40%" }}>{k}</td>
      <td style={{ padding: "7px 4px", borderBottom: "1px solid #e3e6ec", fontWeight: bold ? 700 : 400 }}>{v}</td>
    </tr>
  );
}
